apiVersion : apps/v1
kind: Deployment
metadata:
  name: RSWEBProject 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: RSWEBProject
  template:
    metadata:
      labels:
        app: RSWEBProject
    spec:
      containers:
        - name: RSWEBProject
          image: rswebmvcapp.azurecr.io/RSWEBProject
          ports:
          - containerPort: 80